In [1]:
import numpy as np
#ARANGE FUNCTION
#create array 
#np.arange(start,end,steps)
ar_1d=np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
#to print odd number
print(np.arange(1,13,2))

[ 1  3  5  7  9 11]


In [3]:
#LINESPACE FUNCTION
#to create array which ranges from 1 and upto 5 in between this we want
#4 values 


In [4]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [5]:
#RESHAPE FUNCTION
#to convert 1d array into 2d

In [6]:
arr_2d=ar_1d.reshape(2,6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
#2d array with different combination
arr_2d=ar_1d.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
#1d to 3d
#the dot product of value given should be equal to size of array


In [2]:
arr_3d=ar_1d.reshape(3,4,1)
print(arr_3d)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [10]:
arr_3d=ar_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [11]:
#use arrange and reshape function to create and convert 1d array to 2d
arr=np.arange(1,13)
ar12=arr.reshape(2,6)
print(ar12)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
ar=np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
#RAVEL FUNCTION
#multidimentional array converted to 1d

In [14]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
#FLATTEN() FUNCTION
#it is used for convrting n-dim to 1-dim

In [16]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
#TRANSPOSE FUNCTION
#converting row into column and vice versa

In [18]:
#    ***********************PART 5****************************

In [19]:
#create two similar matrix array
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#do addition elementwise addition
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [21]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [22]:
#u can use same for subtraction 
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#elementwise multiplication
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [26]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [27]:
#matrix multiplication use only @ 

In [28]:
arr1@arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [29]:
#matrix multiplication
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [30]:
#find maximum value in matrix
arr1.max()

9

In [31]:
#maximum value index 
arr1.argmax()

8

In [32]:
#maximum value in row or column(0=column,1=row)

In [33]:
arr1.max(axis=0)
#in colmn 1=7,col2=8,col3=9

array([7, 8, 9])

In [34]:
arr1.max(axis=1)

array([3, 6, 9])

In [35]:
#min can use same as max

In [36]:
#add every element of array and written 1 value

In [37]:
np.sum(arr1)

45

In [38]:
#sum of all col elemnts
np.sum(arr1,axis=0)

array([12, 15, 18])

In [39]:
#sum of all row element
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [40]:
#want average of all array element

In [41]:
np.mean(arr1)

5.0

In [42]:
#find square root of all array element

In [43]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [44]:
#standard deviation
np.std(arr1)

2.581988897471611

In [45]:
#want exponent of every element of array

In [46]:
np.exp(arr1)
#e to the power x

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [47]:
#natural log
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [48]:
#find log base 10
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])