In [1]:
#part 2
import numpy as np

In [2]:
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
type(arr_1d)

numpy.ndarray

In [4]:
arr_1d.ndim

1

In [5]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
arr_2d.ndim

2

In [7]:
arr_2d.size
#the number of elements is shows  is its size

8

In [8]:
arr_2d.shape

(2, 4)

In [9]:
#shape =(row,col)

In [10]:
arr_2d.dtype

dtype('int32')

In [11]:
#///////part 3

In [12]:
#create matrix of 3*3 and 2d array
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
#multiple column single row its just printing ones
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [14]:
#we get output in float type 
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
#we want ones matrix but want integer
mx_1s=np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
mx_0s=np.zeros((3,4),dtype=int)
print(mx_0s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
#bool changes its into o into false and 1 into true
mx_0s=np.zeros((3,4),dtype=bool)
print(mx_0s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [18]:
mx_0s=np.zeros((3,4),dtype=str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [19]:
#when we convert boolean false into string its consider empty string

In [20]:
em_str=''
print(bool(em_str))

False


In [21]:
#create empty matrix
#but its not empty takes random value if its same number of row and column i
em_mx=np.empty((3,3))
print(em_mx)

[[3.97955764e-306 3.97955764e-306 3.34015314e-306]
 [2.32100422e-295 4.26664432e-306 5.45521187e-306]
 [5.58915086e-306 5.45942732e-306 7.79047410e-296]]


In [23]:
#create empty matrix
#but its not empty takes random value
em_mx=np.empty((3,5))
print(em_mx)

[[ 3.25651728e-306  2.73583652e-295 -3.00128777e-231  2.48705585e-301
   3.52188980e-304]
 [-4.29767371e-002  2.75350100e-295  1.22152127e-294  2.41212769e-316
   0.00000000e+000]
 [ 0.00000000e+000  1.54905693e-312              nan  1.23075756e-312
   9.45018094e-308]]
